#!/bin/bash

set -eu
set -o pipefail

readonly ESC=$(printf '\033')
readonly BLUE="${ESC}[34m"
readonly CYAN="${ESC}[36m"
readonly NO_COLOR="${ESC}[m"

declare DEFAULT_BRANCH='main'
git rev-parse --verify -q "${DEFAULT_BRANCH}" >/dev/null 2>&1 || DEFAULT_BRANCH='master'

git_delete_merged_branches() {
  git switch -q "${DEFAULT_BRANCH}"

  local -r branches=$(git branch --merge | grep -v "${DEFAULT_BRANCH}")

  for branch in $branches; do
    git branch -q -d "$branch"
    echo "${BLUE}==> Deleted branch${NO_COLOR} ${CYAN}'${branch}'${NO_COLOR}"
  done
}

git_delete_squashed_branches() {
  git switch -q "${DEFAULT_BRANCH}"

  local -r branches=$(git for-each-ref refs/heads/ "--format=%(refname:short)" | tr '\n' ' ')

  local merge_base
  for branch in $branches; do
    merge_base=$(git merge-base "${DEFAULT_BRANCH}" "${branch}")

    if [[ $(git cherry "${DEFAULT_BRANCH}" "$(git commit-tree "$(git rev-parse "${branch}"^'{tree}')" -p "${merge_base}" -m _)") == "-"* ]]; then
      git branch -q -D "${branch}"
      echo "${BLUE}==> Deleted branch${NO_COLOR} ${CYAN}'${branch}'${NO_COLOR}"
    fi
  done
}

git_refresh() {
  git switch -q "${DEFAULT_BRANCH}"
  git pull origin "${DEFAULT_BRANCH}"

  git_delete_merged_branches
  git_delete_squashed_branches
}

git_refresh "$@"
